name: Build macOS Binaries

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  native:

    runs-on: macos-10.15

    name: macOS binary

    steps:
      - uses: actions/checkout@v2
      - name: set up java ${{ matrix.java-version }}
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 8
      - name: cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build
        run: "rm archive/* && ant jar && ant archive-platform-jar"
      - name: Archive built library
        uses: actions/upload-artifact@v2
        with:
          name: shared-object
          path: build/jni/*.so
      - name: Archive built jar
        uses: actions/upload-artifact@v2
        with:
          name: jar
          path: archive/*.jar

